/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package entry.gradle;

import lombok.Value;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        var user = new User("p1ass", 23);
        System.out.println(user);
    }

    @Value
    public static class User {
        String name;
        int age;
    }
}
